### ISSUE TITLE
test fail to run when using tox locally

### ISSUE THREAD

**Issue by chadrik** [schematics/schematics#418] opened 2016-05-13 19:19 UTC
Not sure if I'm doing something wrong but I get a series of `ImportError` lines if I run `tox` locally.   If I add `tests/__init__.py` then it works again.  I remember reading in either the tox or pytest docs that they recommend not adding this file, but I ran into the same problem on my own project and I could neither find a better solution nor see a down side to adding it.

Also, I found [this tool](https://pypi.python.org/pypi/tox-travis) which makes it easy to setup separate travis jobs for each python environment, so it's more clear when one version fails and the others succeed.  For example, notice the separate Python:2.7 and Python:3.5 jobs here: https://travis-ci.org/chadrik/rill

**Comment by bintoro** [comment] 2016-05-13 19:46
Hmm. What imports is it failing on? The fact that `__init__.py` helps suggests that a local file/folder is masking the name of some module or package.

**Comment by chadrik** [comment] 2016-05-13 21:45
> What imports is it failing on?

sorry, forgot that very vital piece of info.  it fails to import schematics or any of its sub-packages:

```
chad$ tox -r
GLOB sdist-make: /Users/chad/dev/schematics/setup.py
py26 recreate: /Users/chad/dev/schematics/.tox/py26
py26 installdeps: -r/Users/chad/dev/schematics/test-requirements.txt
py26 inst: /Users/chad/dev/schematics/.tox/dist/schematics-2.0.0a1.zip
py26 installed: -f file:///Users/chad/.cache/pip/wheelhouse,argparse==1.4.0,coverage==4.0.3,funcsigs==1.0.2,mock==2.0.0,ordereddict==1.1,pbr==1.9.1,py==1.4.31,pymongo==3.2.2,pytest==2.9.1,python-dateutil==2.5.3,-e git+https://github.com/schematics/schematics@a8249f149b7f2a4963e2c488926e6ccbbd023f43#egg=schematics-origin/development,six==1.10.0,wsgiref==0.1.2
py26 runtests: PYTHONHASHSEED='3120812645'
py26 runtests: commands[0] | py.test
===================================================================== test session starts =====================================================================
platform darwin -- Python 2.6.9, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /Users/chad/dev/schematics, inifile: tox.ini
collected 0 items / 25 errors 

=========================================================================== ERRORS ============================================================================
___________________________________________________________ ERROR collecting tests/test_binding.py ____________________________________________________________
tests/test_binding.py:4: in <module>
    from schematics.models import Model
E   ImportError: No module named schematics.models

[...]
```

then it works if I simply run:

```
touch tests/__init__.py
tox -r
```

You're not seeing this behavior?  Also, I should mention I don't have this problem on the master/1.x branch.

**Comment by bintoro** [comment] 2016-05-14 06:03
No, it works for me. Apparently `tests/__init__.py` used to exist until I removed it a few months ago because it really shouldn't be there.

Why do you have `-e git+https://github.com/schematics/schematics@a8249f149b7f2a4963e2c488926e6ccbbd023f43#egg=schematics-origin/development` in your dependencies?

I tried that, and it seems to confuse the install procedure.

**Comment by chadrik** [comment] 2016-05-14 23:30
This is definitely a strange issue.  To make sure this wasn't caused by a local cache or leftover files in my dev directory, I created a fresh clone of schematics (development branch) and ran `pip uninstall schematics` to get rid of my globally installed copy, but the issue persists.  Deleting the .git directory removed the `-e git+https://github.com/schematics/schematics..` dependency, but also did not fix the issue.  

What versions of tox and pytest are you using?  I'm using the latest from PyPI: tox==2.3.1  and pytest==2.9.1.

**Comment by bintoro** [comment] 2016-05-15 09:51
Okay, this is super odd. The presence of the `.git` directory should be of no consequence to any of this. And I'm still unable to reproduce the issue.

Generally, when working on a project, I have a link to the project directory from the module search path so that I can just run `py.test` and it'll work. I removed the link and made sure `import schematics` fails. `tox` still works fine. Cloning into a fresh directory made no difference. I even deleted the bytecode files to make sure it's running the virtualenv copy.

I've got the same versions of `tox` and `pytest` as you.

All I can think of is that, somehow, the install process fails. If it can't import `schematics`, that would suggest that it didn't install it. I would check if the resulting `schematics/.tox/pyXY/lib/pythonX.Y/site-packages` directory contains `schematics` as it should.

You mentioned having a similar issue with another project, which hints at a system-wide issue. Since `tox` doesn't have any system-wide configuration, maybe it's pip's global configuration that's interfering.

**Comment by bintoro** [comment] 2016-05-17 18:51
After adding `usedevelop = True` in `tox.ini`, I also got

```
-e git+git@github.com:bintoro/schematics.git@8eacb6ec20800d2ae563a88748e6567737119d43#egg=schematics
```

in the `installed: ....` output. The hash belongs to a commit that I haven't even pushed to GitHub, so it looks like this is just tox's way of indicating an `-e` install, which is what I requested with `usedevelop`.

But in your ouput, tox was also doing the regular `setup.py sdist` + install dance. So perhaps the answer lies in figuring out why the two mutually exclusive install methods were indicated at once.

The `-e` install itself, if successful, seems to work fine: https://travis-ci.org/bintoro/schematics/builds/130914725. The dedicated `coverage` run at the end has `usedevelop` enabled.

**Comment by bskinn** [comment] 2016-06-21 21:16
@chadrik, are you using the `PYTHONPATH` env variable to point to your local development directory?

I'm working on getting `tox` set up on my own project, and I've run into exactly [the import problem you're describing](https://github.com/schematics/schematics/issues/418#issuecomment-219167031).

I haven't nailed down exactly what's going on, but if I have `PYTHONPATH` set to my project's folder, it appears to confuse `pip` and/or `tox` somehow. The upshot is that my package ends up not being installed into the virtualenvs.  Clearing `PYTHONPATH` before calling `tox`, or manually running `pip install --force-reinstall` on each virtualenv, seems to make things play nice. Probably `PYTHONPATH` can be overridden in `tox.ini` somewhere, I just haven't gotten to that point yet.

**Comment by bskinn** [comment] 2016-06-23 02:18
**If this is your problem, the fix is simple:** Add the following to `tox.ini`:

```
setenv=
    PYTHONPATH=
```

**Some more detail:**

My normal `PYTHONPATH`:

```
$ echo $PYTHONPATH
/home/pydev/py/opan:
```

`tox` output with `PYTHONPATH` set:

```
GLOB sdist-make: /home/pydev/py/opan/setup.py
py35-h26-n1.11-s0.17 create: /home/pydev/py/opan/.tox/py35-h26-n1.11-s0.17
py35-h26-n1.11-s0.17 installdeps: Cython, numpy>=1.11,<1.12, scipy>=0.17,<0.18
py35-h26-n1.11-s0.17 inst: /home/pydev/py/opan/.tox/dist/opan-0.4.0.zip
py35-h26-n1.11-s0.17 installed: Cython==0.24,numpy==1.11.0,opan==0.4.0,scipy==0.17.1
py35-h26-n1.11-s0.17 runtests: PYTHONHASHSEED='2725425217'
py35-h26-n1.11-s0.17 runtests: commands[0] | pip install h5py>=2.6,<2.7
Collecting h5py<2.7,>=2.6
Collecting six (from h5py<2.7,>=2.6)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.1 in /home/pydev/py/opan/.tox/py35-h26-n1.11-s0.17/lib/python3.5/site-packages (from h5py<2.7,>=2.6)
Installing collected packages: six, h5py
Successfully installed h5py-2.6.0 six-1.10.0
py35-h26-n1.11-s0.17 runtests: commands[1] | python tests.py --all
Traceback (most recent call last):
  File "tests.py", line 22, in <module>
    import unittest, opan.test
ImportError: No module named 'opan'
ERROR: InvocationError: '/home/pydev/py/opan/.tox/py35-h26-n1.11-s0.17/bin/python tests.py --all'
___________________________________ summary ____________________________________
ERROR:   py35-h26-n1.11-s0.17: commands failed
```

`pip freeze` inside the `tox` virtualenv, with and without `PYTHONPATH` set:

```
$ source .tox/py35-h26-n1.11-s0.17/bin/activate
(py35-h26-n1.11-s0.17) $ pip freeze
Cython==0.24
h5py==2.6.0
numpy==1.11.0
opan==0.4.0
scipy==0.17.1
six==1.10.0
(py35-h26-n1.11-s0.17) $ PYTHONPATH=
(py35-h26-n1.11-s0.17) $ pip freeze
Cython==0.24
h5py==2.6.0
numpy==1.11.0
scipy==0.17.1
six==1.10.0
```

Indeed, the package has not been installed inside the virtualenv:

```
$ ls -1 .tox/py35-h26-n1.11-s0.17/lib/python3.5/site-packages/
Cython
Cython-0.24.dist-info
cython.py
easy_install.py
h5py
h5py-2.6.0.dist-info
numpy
numpy-1.11.0.dist-info
pip                    <===== SHOULD BE ABOVE THIS LINE
pip-8.1.2.dist-info
pkg_resources
__pycache__
pyximport
scipy
scipy-0.17.1.dist-info
setuptools
setuptools-23.0.0.dist-info
six-1.10.0.dist-info
six.py
wheel
wheel-0.29.0.dist-info
```

`tox` output with `PYTHONPATH` cleared:

```
GLOB sdist-make: /home/pydev/py/opan/setup.py
py35-h26-n1.11-s0.17 recreate: /home/pydev/py/opan/.tox/py35-h26-n1.11-s0.17
py35-h26-n1.11-s0.17 installdeps: Cython, numpy>=1.11,<1.12, scipy>=0.17,<0.18
py35-h26-n1.11-s0.17 inst: /home/pydev/py/opan/.tox/dist/opan-0.4.0.zip
py35-h26-n1.11-s0.17 installed: Cython==0.24,numpy==1.11.0,opan==0.4.0,scipy==0.17.1
py35-h26-n1.11-s0.17 runtests: PYTHONHASHSEED='1675986189'
py35-h26-n1.11-s0.17 runtests: commands[0] | pip install h5py>=2.6,<2.7
Collecting h5py<2.7,>=2.6
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.1 in /home/pydev/py/opan/.tox/py35-h26-n1.11-s0.17/lib/python3.5/site-packages (from h5py<2.7,>=2.6)
Collecting six (from h5py<2.7,>=2.6)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, h5py
Successfully installed h5py-2.6.0 six-1.10.0
py35-h26-n1.11-s0.17 runtests: commands[1] | python tests.py --all
..............................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 318 tests in 2.791s

OK
__________________________________________________________________________________________ summary __________________________________________________________________________________________
  py35-h26-n1.11-s0.17: commands succeeded
  congratulations :)
```

**Hazarded explanation:**
I'm guessing when `tox` calls `pip` with `PYTHONPATH` defined, `pip` sees the package as already installed at the current version, and so it doesn't actually install the newly built dist into the virtualenv, even though it doesn't actually exist there.  Then, for whatever internal reason, when `tox` calls python` within the virtualenv, the `python` instance doesn't have visibility to the `PYTHONPATH` env variable in the outer scope, and so the `import opan.test` call fails with the `ImportError`.

**Comment by lkraider** [comment] 2017-05-23 01:53
Thanks for the info @bskinn , closing as a configuration issue.

**Closed by lkraider** 2017-05-23 01:53 UTC

**Comment by scottschreckengaust** [comment] 2018-02-15 22:12
I found this message when there were no tests...add a test and see if it works?
