### ISSUE TITLE
Update the documentation for schematics

### ISSUE THREAD

**Issue by kracekumar** [schematics/schematics#302] opened 2015-04-20 19:17 UTC
This issue is to track the changes required to documentation infrastructure, missing documentation for features etc ... If you find any thing specific to documentation is missing, please comment.

**Comment by apranav19** [comment] 2015-04-21 21:29
@kracekumar Thanks for opening up this ticket. I'll update this soon!

**Comment by jmsdnns** [comment] 2015-04-27 19:49
While doing this, would you mind pulling out the "what's with the fork?" section? It's no longer necessary since evidence of this project being a fork is no longer visible.

**Comment by kracekumar** [comment] 2015-04-27 20:00
Sure.

On Tue, Apr 28, 2015 at 1:19 AM, Jms Dnns <notifications@github.com> wrote:

> While doing this, would you mind pulling out the "what's with the fork?"
> section? It's no longer necessary since evidence of this project being a
> fork is no longer visible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/issues/302#issuecomment-96795502>
> .
>



-- 
Regards
Kracekumar Ramaraju
http://kracekumar.com
+91 85530 29521

**Comment by bintoro** [comment] 2015-11-01 23:53
I'm in the process of fixing a few things with the docs, and I noticed the "latest" version on Read the Docs is connected to the master branch. Given that almost nothing goes on in `master` besides a release every now and then, I think "latest" should point to the `development` branch instead.

**Comment by bintoro** [comment] 2015-11-02 23:38
Okay, so I've overhauled the documentation structure so that we now have a proper TOC that's always visible in the navbar. Content-wise just a few updates, nothing big yet.

The new docs can be viewed rendered [here](https://rawgit.com/schematics/schematics/fbe1684cf886d2ac2d926be2d5dede42ea7c00af/docs/_build/html/index.html).

Ping @jmsdnns, if you agree on the "latest" → `development` / "stable" → `master` setup, could you change the settings on RTD when you have time?

**Comment by jmsdnns** [comment] 2015-11-02 23:49
Great work!

I agree with latest being dev and stable being master.

So I can adjust those settings, but I'm wondering if perhaps we should just
push into master more frequently?

I tried building the docs against latest and it seems RTD failed it. Here
is the output: https://readthedocs.org/projects/schematics/builds/3450649/

On Mon, Nov 2, 2015 at 6:38 PM, Kalle Tuure <notifications@github.com>
wrote:

> Okay, so I've overhauled the documentation structure so that we now have a
> proper TOC that's always visible in the navbar. Content-wise just a few
> updates, nothing big yet.
>
> The new docs can be viewed rendered here
> <https://rawgit.com/schematics/schematics/fbe1684cf886d2ac2d926be2d5dede42ea7c00af/docs/_build/html/index.html>
> .
>
> Ping @jmsdnns <https://github.com/jmsdnns>, if you agree on the "latest"
> → development / "stable" → master setup, could you change the settings on
> RTD when you have time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schematics/schematics/issues/302#issuecomment-153193819>
> .
>



-- 
jms dnns
me <http://jmsdnns.com> // facebook <https://www.facebook.com/jmsdnns> //
github <https://github.com/jmsdnns/> // twitter
<https://twitter.com/jmsdnns>

**Comment by bintoro** [comment] 2015-11-02 23:54
Interesting, as I hadn't pushed anything to the main repo branches yet. I'll merge the new docs now and try to get it to work.

**Comment by bintoro** [comment] 2015-11-03 00:59
RTD was using some Sphinx argument that didn't exist in the ancient version that was specified in the Schematics requirements file. It was just a coincidence it had broken now. Fixed via #348. The docs are now live.

**Comment by rooterkyberian** [comment] 2017-09-22 15:01
The http://schematics.readthedocs.io/ was last updated over a year ago. It seems this situation is in part caused by the fact most active contributor at the moment (@lkraider) is lacking necessary access to fix things (https://github.com/schematics/schematics/issues/513#issuecomment-327011144).

Should I open a new Issue for this instead of reviving this two year old one, which certainly wasn't created for this particular instance of the problem in mind?
IMHO its better to keep issue concise and very specific to a problem at the moment instead of having a long standing, never ending "tasks".

**Comment by bintoro** [comment] 2017-09-22 15:04
@lkraider now has admin rights on readthedocs.

**Comment by lkraider** [comment] 2017-09-22 18:31
Updated the latest build and also the tagged versions there. Next builds should work automatically.

**Closed by lkraider** 2017-09-22 18:31 UTC
Labels: documentation
